const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const authModal=$('#authModal'),cartModal=$('#cartModal'),reserveModal=$('#reserveModal');let authMode='login',cart=[];
function modalOpen(m){m.classList.add('open');document.body.style.overflow='hidden'}function modalClose(m){m.classList.remove('open');if(!$('.modal-backdrop.open'))document.body.style.overflow=''}
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>modalClose(b.closest('.modal-backdrop'))));
$$('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)modalClose(m)}));
function setAuth(mode){authMode=mode;$('#authTitle').textContent=mode==='login'?'Welcome back.':'Join our table.';$('#authDesc').textContent=mode==='login'?'Log in to make your next visit special.':'Create an account for a little more Saffron House.';$('#authName').parentElement.style.display=mode==='signup'?'grid':'none';$('#authName').required=mode==='signup';$('#authSubmit').textContent=mode==='login'?'Log in ↗':'Create account ↗';$('#authSwitch').innerHTML=mode==='login'?'New here? <button type="button">Sign up</button>':'Already a member? <button type="button">Log in</button>';$('#authSwitch button').onclick=()=>setAuth(mode==='login'?'signup':'login')}
$('#loginOpen').onclick=()=>{setAuth('login');modalOpen(authModal)};$('#signupOpen').onclick=()=>{setAuth('signup');modalOpen(authModal)};setAuth('login');
$('#authForm').addEventListener('submit',e=>{e.preventDefault();toast(authMode==='login'?'Demo login complete ✳':'Demo account created ✳');modalClose(authModal);e.target.reset()});
$$('.filter').forEach(btn=>btn.addEventListener('click',()=>{$$('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;$$('.dish').forEach(d=>d.classList.toggle('hidden',f!=='all'&&d.dataset.category!==f))}));
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2100)}
$$('.add-btn').forEach(b=>b.addEventListener('click',()=>{const found=cart.find(x=>x.name===b.dataset.name);if(found)found.qty++;else cart.push({name:b.dataset.name,price:+b.dataset.price,qty:1});renderCart();toast('Added to your order ✳')}));
function renderCart(){$('#cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0);$('#cartItems').innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row"><span>${x.name} <small>× ${x.qty}</small></span><span>₹${x.price*x.qty} <button data-remove="${i}" aria-label="Remove">×</button></span></div>`).join(''):'Your basket is empty.';$('#cartTotal').textContent='₹'+cart.reduce((a,x)=>a+x.price*x.qty,0);$$('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.remove,1);renderCart()})}
$('#viewCart').onclick=()=>{renderCart();modalOpen(cartModal)};$('#checkout').onclick=()=>{if(!cart.length){toast('Add a dish to continue');return}toast('Demo checkout — no payment taken');modalClose(cartModal)};
$('#reserveOpen').onclick=()=>modalOpen(reserveModal);$('#reserveDate').min=new Date().toISOString().split('T')[0];$('#reserveForm').addEventListener('submit',e=>{e.preventDefault();toast('Reservation request noted (demo) ✳');modalClose(reserveModal);e.target.reset()});
$('#hamburger').onclick=()=>$('#nav').classList.toggle('open');$$('#nav a').forEach(a=>a.addEventListener('click',()=>$('#nav').classList.remove('open')));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(el=>observer.observe(el));
document.addEventListener('pointermove',e=>{document.documentElement.style.setProperty('--mx',e.clientX+'px');document.documentElement.style.setProperty('--my',e.clientY+'px')});
document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.modal-backdrop.open').forEach(modalClose)});
